##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_type
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_type
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/RobertMollentze
- https://github.com/sponsors/robmllze
description: Simplifies type conversions, inspections, nested data access, sync/async operations and more.
version: 0.14.2
topics:
  - data
  - easy-packages
  - tool
  - utility
  - utils

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

